### ISSUE TITLE
Recopilar los métodos de predicción de series temporales que haya en R y en Weka

### ISSUE THREAD

**Issue by pacastillo** [geneura-papers/2015_sipesca-b#1]
Recopilar los métodos de predicción de series temporales que haya en R y en Weka para usarlos con varias series publicadas y sacar "resultados base".

**Comment by deantares** [comment]
Voy añadiendo en este comentario a medida que tenga más información sobre ellos. De momento, he mirado los algoritmos que permite WEKA elegir como **Base learner configuration** y que permiten predecir valores numéricos.

### Weka
- Basados en funciones
  - Gaussian Processes
  - Linear regresion
  - MultilayerPerceptron
  - SMOreg
- Lazy
  - IBK
  - KStar
  - LWL
- Meta
  - AdditiveRegresion
  - Bagging
  - CVParameterSelection
  - MultiScheme
  - RandomSubSpace
  - RegressionByDiscretization
  - Stacking
  - Vote
- Misc
  - InputMappedClassifier
- Rules
  - DecisionTable
  - M5Rules
  - ZeroR
- Trees
  - DecisionStump
  - M5P
  - REPTree

## R - forecast
- ARFIMA
- ARIMA
- CROSTON
- HOLT-WINTERS
- ETS - Exponential smoothing
- BATS 
- Linear Model
- STL Objects ¿?

**Comment by pacastillo** [comment]
Revisar también:

https://www.otexts.org/fpp/8
  8.7 ARIMA modelling in R
  8.8 Forecasting
  8.9 Seasonal ARIMA models
  8.10 ARIMA vs ETS

https://www.otexts.org/fpp/9
  9.1 Dynamic regression models
  9.2 Vector autoregressions
  9.3 Neural network models
  9.4 Forecasting hierarchical or grouped time series

**Comment by JJ** [comment]
Mirad también complex event processing y market-basket analysis. Tenéis también eventos discretos (este coche pasa por este sitio) y conjuntos (este ID pasa junto con ese) así que se pueden analizar también.

**Comment by JasgTrilla** [comment]
Hola, quien me dice como funciona el algoritmo SMOreg, quisiera saber si trabaja con redes neuronales, o arboles de decision etc.... y cualquier detalle que me puedan dar.
Gracias

**Comment by deantares** [comment]
Trabaja con máquinas de vector soporte o "support vector machine". Puedes ver estos artículos para saber más:

 @inproceedings{Shevade1999,
    author = {S.K. Shevade and S.S. Keerthi and C. Bhattacharyya and K.R.K. Murthy},
    booktitle = {IEEE Transactions on Neural Networks},
    title = {Improvements to the SMO Algorithm for SVM Regression},
    year = {1999},
    PS = {http://guppy.mpe.nus.edu.sg/\~mpessk/svm/ieee_smo_reg.ps.gz}
 }
 
 @techreport{Smola1998,
    author = {A.J. Smola and B. Schoelkopf},
    note = {NeuroCOLT2 Technical Report NC2-TR-1998-030},
    title = {A tutorial on support vector regression},
    year = {1998}
 }

**Comment by JasgTrilla** [comment]
Muchas Gracias (Y)
