### ISSUE TITLE
Justificar que nuestro conjunto de datos es más útil que los que ofrecen otros

### ISSUE THREAD

**Issue by pacastillo** [geneura-papers/2015_sipesca-b#2]
He encontrado otros repositorios en los que se facilitan series temporales hechas con datos reales, pero a partir de aforadores de espiras. Eso significa que cuentan muy bien los vehículos pero no los individualizan.

Ahí es donde nosotros ofrecemos un punto diferenciador: con nuestros datos se pueden hacer series temporales de datos reales, y además se pueden individualizar los vehículos, pudiendo hacer matrices de E/S, o hacer seguimientos de vehículos para ver qué recorridos hacer, con qué frecuencia, etc, etc.

¡Esto es lo que tenemos que conseguir vender con nuestro benchmark!
Y aquí es donde necesito el "brainstorming"    ;)

**Comment by deantares** [comment]
Okis, deberíamos intentar sacar no sólo series temporales de un nodo, si no
de trayectos.

Tomo nota 😉

**Comment by pacastillo** [comment]
¡¡¡gracias!!!
No he asignado el issue para que todos aportemos  ;)

**Comment by JJ** [comment]
Pero para justificar que sea útil tiene que cubrir una necesidad. Por
ejemplo, hay algoritmos que modelizan el tráfico en un nodo a partir del
tráfico en otros nodos... podía servir para eso. O para hacer grafos de
conectividad de ciudades.

**Comment by JJ** [comment]
Mirad por ejemplo este sistema de simulación:
https://www.researchgate.net/profile/Pawet_Gora/publication/233380378_Traffic_Simulation_Framework_-_a_cellular_automaton-based_tool_for_simulating_and_investigating_real_city_traffic/links/00b7d5322ba52e70e3000000.pdf
Quizás habría que ver la forma en que estos sistemas de simulación generan
datos para ajustarlos a los nuestros o al revés...
También te puede decir qué es imprescindible cubrir con sensores para tener
una idea del tráfico completa, sin necesidad de cubrir todas las entradas y
salidas.

**Comment by JJ** [comment]
Mirad también este http://arxiv.org/pdf/cond-mat/9905216.pdf en el que
habla de los tres "modos" del flujo del tráfico: fluido, "parada y vuelta a
andar" y "sincronizado". ¿Se podrían usar los datos para detectar este tipo
de estado? Sería como el iris y el de la diabetes, pero en tráfico.

**Comment by JJ** [comment]
Mirad también este
@incollection{nakayama2003optimal,
  title={Optimal Velocity Model and its Applications},
  author={Nakayama, A and Hasebe, K and Sugiyama, Y},
  booktitle={Traffic and Granular Flow’01},
  pages={127--140},
  year={2003},
  publisher={Springer}
}

**Comment by JJ** [comment]
Por cierto que he encontrado todo esto en StackExchange:
http://opendata.stackexchange.com/questions/1767/data-of-vehicle-traffic

**Comment by mgarenas** [comment]
Se me ocurre que si sacamos datos de los dispositivos que pasan por más 
de un nodo diferente, y tenemos suerte y sacamos ... no sé, 100 
dispositivos que pasan por al menos 3 nodos diferentes... podriamos 
hacer una matriz en vez de una serie, quitándo el número de dispositivo 
e intentar predecir eso, tomando cada mini serie de forma independiente, 
pero la verdad es que no sé qué saldrá.

Maribel

On 06/04/15 16:49, Pedro A. Castillo Valdivieso wrote:

> ¡¡¡gracias!!!
> No he asignado el issue para que todos aportemos ;)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/geneura-papers/2015_sipesca-b/issues/2#issuecomment-90086290.

## 

"Este mensaje se dirige exclusivamente a su destinatario y puede 
contener información privilegiada o confidencial. Si no es Ud. el 
destinatario indicado, queda notificado de que la utilización, 
divulgación o copia sin autorización está prohibida en virtud de la 
legislación vigente. Si ha recibido este mensaje por error, se ruega lo 
comunique inmediatamente por esta misma vía y proceda a su destrucción.

This message is intended exclusively for its addressee and may contain 
information that is CONFIDENTIAL and protected by professional 
privilege. If you are not the intended recipient you are hereby notified 
that any dissemination, copy or disclosure of this communication is 
strictly prohibited by law. If this message has been received in error, 
please inmediately notify us via e-mail and delete it"

María Isabel García Arenas
Dpto. Arquitectura y Tecnología de los Computadores
Universidad de Granada
