### ISSUE TITLE
Estado del arte: informe americano 

### ISSUE THREAD

**Issue by JJ** [geneura-papers/2015_sipesca-b#4]
Informe súper completo de métodos de detección, terminología y 7 cosas más http://www.fhwa.dot.gov/policyinformation/tmguide/tmg_2013/traffic-monitoring-theory.cfm#TERMINOLOGY

**Comment by fergunet** [comment]
Muy interesante. Algún voluntario para revisar y resumir y explicarlo en una reunión del lunes?

**Comment by JJ** [comment]
Nos quedan muchos lunes. ¿Quién se anima?

**Comment by fergunet** [comment]
A pesar de que prefiero que se centre en los cacharros y los deje listo para colocarlos este mes en la carretera creo que quien debería hacerlo es @deantares ya que es su tesis y él debe convertirse en el experto del grupo :)

(Perdón por el marrón! xD)
